package Vista;

public class Factura extends javax.swing.JPanel {

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        panel_pagos = new Vista.PanelesRedondeados();
        paneleCobro = new Vista.PanelesRedondeados();
        txt_cobrar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Factura = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(780, 540));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_pagos.setBackground(new java.awt.Color(235, 235, 235));
        panel_pagos.setBordeInferiorDerecho(50);
        panel_pagos.setBordeInferiorIzquierdo(50);
        panel_pagos.setBordeSuperiorDerecho(50);
        panel_pagos.setBordeSuperiorIzquierdo(50);
        panel_pagos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneleCobro.setBackground(new java.awt.Color(200, 200, 200));
        paneleCobro.setBordeInferiorDerecho(50);
        paneleCobro.setBordeInferiorIzquierdo(50);
        paneleCobro.setBordeSuperiorDerecho(50);
        paneleCobro.setBordeSuperiorIzquierdo(50);
        paneleCobro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cobrar.setBackground(new java.awt.Color(187, 187, 187));
        txt_cobrar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txt_cobrar.setForeground(new java.awt.Color(0, 0, 0));
        txt_cobrar.setText("Cobrar ");
        paneleCobro.add(txt_cobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        Factura.setEditable(false);
        Factura.setBackground(new java.awt.Color(235, 235, 235));
        Factura.setColumns(20);
        Factura.setRows(5);
        jScrollPane1.setViewportView(Factura);

        paneleCobro.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 400, 270));

        panel_pagos.add(paneleCobro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 630, 420));

        Background.add(panel_pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 750, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    public static javax.swing.JTextArea Factura;
    private javax.swing.JScrollPane jScrollPane1;
    private Vista.PanelesRedondeados panel_pagos;
    private Vista.PanelesRedondeados paneleCobro;
    private javax.swing.JLabel txt_cobrar;
    // End of variables declaration//GEN-END:variables
}
