package Vista;

import Control.ControlUsuario;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

public class Pagos extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Pagos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        panel_pagos = new Vista.PanelesRedondeados();
        panelesRedondeados1 = new Vista.PanelesRedondeados();
        txt_pagos = new javax.swing.JLabel();
        Cliente = new javax.swing.JLabel();
        Placas = new javax.swing.JLabel();
        valor_cancela = new javax.swing.JLabel();
        box_valor_Cancelar_Pago = new javax.swing.JTextField();
        jSeparatorIdentificacion = new javax.swing.JSeparator();
        ver_Actualizar_propietario = new Vista.PanelesRedondeados();
        btn_actualizar_ista = new javax.swing.JLabel();
        box_despegable_nom = new javax.swing.JComboBox<>();
        ver_Actualizar_placa = new Vista.PanelesRedondeados();
        btn_actualizar_lista_placa = new javax.swing.JLabel();
        box_despegable_placa = new javax.swing.JComboBox<>();
        panelesRedondeados2 = new Vista.PanelesRedondeados();
        txt_Vehiculo1 = new javax.swing.JLabel();
        Box_Describa_pago = new javax.swing.JTextField();
        Generar_pago = new javax.swing.JPanel();
        btn_generar_pago = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(780, 540));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_pagos.setBackground(new java.awt.Color(235, 235, 235));
        panel_pagos.setBordeInferiorDerecho(50);
        panel_pagos.setBordeInferiorIzquierdo(50);
        panel_pagos.setBordeSuperiorDerecho(50);
        panel_pagos.setBordeSuperiorIzquierdo(50);
        panel_pagos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelesRedondeados1.setBackground(new java.awt.Color(200, 200, 200));
        panelesRedondeados1.setBordeInferiorDerecho(50);
        panelesRedondeados1.setBordeInferiorIzquierdo(50);
        panelesRedondeados1.setBordeSuperiorDerecho(50);
        panelesRedondeados1.setBordeSuperiorIzquierdo(50);
        panelesRedondeados1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_pagos.setBackground(new java.awt.Color(187, 187, 187));
        txt_pagos.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txt_pagos.setText("Pagos");
        panelesRedondeados1.add(txt_pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        Cliente.setBackground(new java.awt.Color(0, 0, 0));
        Cliente.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Cliente.setText("Cliente");
        panelesRedondeados1.add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        Placas.setBackground(new java.awt.Color(0, 0, 0));
        Placas.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Placas.setText("Placa");
        panelesRedondeados1.add(Placas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        valor_cancela.setBackground(new java.awt.Color(0, 0, 0));
        valor_cancela.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        valor_cancela.setText("Valor a cancelar");
        panelesRedondeados1.add(valor_cancela, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        box_valor_Cancelar_Pago.setBackground(new java.awt.Color(200, 200, 200));
        box_valor_Cancelar_Pago.setForeground(new java.awt.Color(112, 123, 124));
        box_valor_Cancelar_Pago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        box_valor_Cancelar_Pago.setText("$ 45000");
        box_valor_Cancelar_Pago.setBorder(null);
        box_valor_Cancelar_Pago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box_valor_Cancelar_PagoMousePressed(evt);
            }
        });
        box_valor_Cancelar_Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_valor_Cancelar_PagoActionPerformed(evt);
            }
        });
        panelesRedondeados1.add(box_valor_Cancelar_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 300, -1));
        panelesRedondeados1.add(jSeparatorIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 350, 10));

        ver_Actualizar_propietario.setBackground(new java.awt.Color(190, 190, 190));
        ver_Actualizar_propietario.setBordeInferiorDerecho(15);
        ver_Actualizar_propietario.setBordeInferiorIzquierdo(10);
        ver_Actualizar_propietario.setBordeSuperiorDerecho(15);
        ver_Actualizar_propietario.setBordeSuperiorIzquierdo(10);
        ver_Actualizar_propietario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_actualizar_ista.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_actualizar_ista.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar_ista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_actualizar_ista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        btn_actualizar_ista.setText("Actualizar");
        btn_actualizar_ista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_actualizar_ista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_actualizar_istaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_actualizar_istaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_actualizar_istaMousePressed(evt);
            }
        });
        ver_Actualizar_propietario.add(btn_actualizar_ista, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        panelesRedondeados1.add(ver_Actualizar_propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 120, 33));

        box_despegable_nom.setBackground(new java.awt.Color(235, 235, 235));
        box_despegable_nom.setMaximumRowCount(100);
        box_despegable_nom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Propietario" }));
        box_despegable_nom.setToolTipText("");
        box_despegable_nom.setAutoscrolls(true);
        box_despegable_nom.setBorder(null);
        box_despegable_nom.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        box_despegable_nom.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        box_despegable_nom.setLightWeightPopupEnabled(false);
        box_despegable_nom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                box_despegable_nomMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                box_despegable_nomMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box_despegable_nomMousePressed(evt);
            }
        });
        box_despegable_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_despegable_nomActionPerformed(evt);
            }
        });
        panelesRedondeados1.add(box_despegable_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 270, 32));

        ver_Actualizar_placa.setBackground(new java.awt.Color(190, 190, 190));
        ver_Actualizar_placa.setBordeInferiorDerecho(15);
        ver_Actualizar_placa.setBordeInferiorIzquierdo(10);
        ver_Actualizar_placa.setBordeSuperiorDerecho(15);
        ver_Actualizar_placa.setBordeSuperiorIzquierdo(10);
        ver_Actualizar_placa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_actualizar_lista_placa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_actualizar_lista_placa.setForeground(new java.awt.Color(255, 255, 255));
        btn_actualizar_lista_placa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_actualizar_lista_placa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        btn_actualizar_lista_placa.setText("Actualizar");
        btn_actualizar_lista_placa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_actualizar_lista_placa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_actualizar_lista_placaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_actualizar_lista_placaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_actualizar_lista_placaMousePressed(evt);
            }
        });
        ver_Actualizar_placa.add(btn_actualizar_lista_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        panelesRedondeados1.add(ver_Actualizar_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 113, 120, 33));

        box_despegable_placa.setBackground(new java.awt.Color(235, 235, 235));
        box_despegable_placa.setMaximumRowCount(100);
        box_despegable_placa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Propietario" }));
        box_despegable_placa.setToolTipText("");
        box_despegable_placa.setAutoscrolls(true);
        box_despegable_placa.setBorder(null);
        box_despegable_placa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        box_despegable_placa.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        box_despegable_placa.setLightWeightPopupEnabled(false);
        box_despegable_placa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                box_despegable_placaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                box_despegable_placaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box_despegable_placaMousePressed(evt);
            }
        });
        box_despegable_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_despegable_placaActionPerformed(evt);
            }
        });
        panelesRedondeados1.add(box_despegable_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 113, 270, 32));

        panel_pagos.add(panelesRedondeados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 570, 240));

        panelesRedondeados2.setBackground(new java.awt.Color(200, 200, 200));
        panelesRedondeados2.setBordeInferiorDerecho(50);
        panelesRedondeados2.setBordeInferiorIzquierdo(50);
        panelesRedondeados2.setBordeSuperiorDerecho(50);
        panelesRedondeados2.setBordeSuperiorIzquierdo(50);

        txt_Vehiculo1.setBackground(new java.awt.Color(187, 187, 187));
        txt_Vehiculo1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txt_Vehiculo1.setText("Descripcion");

        Box_Describa_pago.setBackground(new java.awt.Color(235, 235, 235));
        Box_Describa_pago.setForeground(new java.awt.Color(112, 123, 124));
        Box_Describa_pago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Box_Describa_pago.setText("Aqui puede dar una breve descripcion del pago ");
        Box_Describa_pago.setBorder(null);
        Box_Describa_pago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Box_Describa_pagoMousePressed(evt);
            }
        });
        Box_Describa_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_Describa_pagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelesRedondeados2Layout = new javax.swing.GroupLayout(panelesRedondeados2);
        panelesRedondeados2.setLayout(panelesRedondeados2Layout);
        panelesRedondeados2Layout.setHorizontalGroup(
            panelesRedondeados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelesRedondeados2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txt_Vehiculo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelesRedondeados2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(Box_Describa_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        panelesRedondeados2Layout.setVerticalGroup(
            panelesRedondeados2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelesRedondeados2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txt_Vehiculo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Box_Describa_pago, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        panel_pagos.add(panelesRedondeados2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 570, 160));

        Generar_pago.setBackground(new java.awt.Color(18, 90, 173));
        Generar_pago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Generar_pago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Generar_pagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Generar_pagoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Generar_pagoMousePressed(evt);
            }
        });
        Generar_pago.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_generar_pago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_generar_pago.setForeground(new java.awt.Color(255, 255, 255));
        btn_generar_pago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_generar_pago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/factura.png"))); // NOI18N
        btn_generar_pago.setText("Generar Pago");
        btn_generar_pago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_generar_pagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_generar_pagoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_generar_pagoMousePressed(evt);
            }
        });
        Generar_pago.add(btn_generar_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 30));

        panel_pagos.add(Generar_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 440, 160, 33));

        Background.add(panel_pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 750, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void box_valor_Cancelar_PagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box_valor_Cancelar_PagoMousePressed
        if (box_valor_Cancelar_Pago.getText().equals("$ 45000")) {

            box_valor_Cancelar_Pago.setText("");
            box_valor_Cancelar_Pago.setForeground(Color.BLACK);

        }
    }//GEN-LAST:event_box_valor_Cancelar_PagoMousePressed

    private void box_valor_Cancelar_PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_valor_Cancelar_PagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_valor_Cancelar_PagoActionPerformed

    private void Box_Describa_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_Describa_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_Describa_pagoActionPerformed

    private void btn_generar_pagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_generar_pagoMouseEntered
        Generar_pago.setBackground(new Color(115, 198, 182));
        btn_generar_pago.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_generar_pagoMouseEntered

    private void btn_generar_pagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_generar_pagoMouseExited
        Generar_pago.setBackground(new Color(18, 90, 173));
        btn_generar_pago.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_generar_pagoMouseExited

    private void Generar_pagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Generar_pagoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Generar_pagoMouseEntered

    private void Generar_pagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Generar_pagoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Generar_pagoMouseExited

    private void Generar_pagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Generar_pagoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Generar_pagoMousePressed
    String cliente = "";
    String placa = "";
    String valor = "";
    String pago = "";

    private void btn_generar_pagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_generar_pagoMousePressed
        int respuesta;

        respuesta = JOptionPane.showConfirmDialog(null, "¿Los datos son correctos?, ¿Esta seguro de generar la factura?", "Advertencia", JOptionPane.YES_NO_OPTION);

        if (respuesta == 0) {
            /* para que nos permita dejar pasar de panel a panlel tenenmos que comvertir el jpanel panel contenedor en  la clase portal
        en protegido o publico y chulear que sea estatico una ves cambiemos esta configuracion en cuztomice codigo nos permitira 
        facil mente ir de un lado al otro con el boton
             */
            Factura pagos = new Factura(); //tamaño del panel
            Portal Panel = new Portal();  //posicion dentro del panel principal 

            pagos.setSize(780, 540);
            pagos.setLocation(0, 0);

            Panel.PanelContenedor.removeAll();
            Panel.PanelContenedor.add(pagos, BorderLayout.CENTER);
            Panel.PanelContenedor.revalidate();
            Panel.PanelContenedor.repaint();

            cliente = box_despegable_nom.getSelectedItem().toString();

            placa = box_despegable_placa.getSelectedItem().toString();
            valor = box_valor_Cancelar_Pago.getText();
            pago = Box_Describa_pago.getText();

            Facturas(pagos.Factura);

        }
    }//GEN-LAST:event_btn_generar_pagoMousePressed

    public void Facturas(JTextArea factura) {

        factura.append("-------------------------------------------Factura-----------------------------------------");
        factura.append("\n\n\n");
        factura.append("  Nombre del propietario:\t  " + cliente);
        factura.append("\n\n");
        factura.append("  Placa del Vehiculo:\t  " + placa);
        factura.append("\n\n");
        factura.append("  el valor a pagar por el mes es: $ " + valor);

        factura.append("\n\n\n");
        factura.append("----------------------------------------Descripcion--------------------------------------");
        factura.append("\n" + pago);
    }
    private void Box_Describa_pagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Box_Describa_pagoMousePressed
        if (Box_Describa_pago.getText().equals("Aqui puede dar una breve descripcion del pago ")) {
            Box_Describa_pago.setText("");
            Box_Describa_pago.setForeground(Color.black);
        }
    }//GEN-LAST:event_Box_Describa_pagoMousePressed

    private void box_despegable_nomMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box_despegable_nomMouseEntered

    }//GEN-LAST:event_box_despegable_nomMouseEntered

    private void box_despegable_nomMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box_despegable_nomMouseExited

    }//GEN-LAST:event_box_despegable_nomMouseExited

    private void box_despegable_nomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box_despegable_nomMousePressed

    }//GEN-LAST:event_box_despegable_nomMousePressed

    private void box_despegable_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_despegable_nomActionPerformed

    }//GEN-LAST:event_box_despegable_nomActionPerformed

    private void btn_actualizar_istaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizar_istaMouseEntered
        btn_actualizar_ista.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_actualizar_istaMouseEntered

    private void btn_actualizar_istaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizar_istaMouseExited
        btn_actualizar_ista.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_actualizar_istaMouseExited

    private void btn_actualizar_istaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizar_istaMousePressed
        new ControlUsuario().llenarListaBoxFacturaPropietario(box_despegable_nom);
    }//GEN-LAST:event_btn_actualizar_istaMousePressed

    private void box_despegable_placaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box_despegable_placaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_box_despegable_placaMouseEntered

    private void box_despegable_placaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box_despegable_placaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_box_despegable_placaMouseExited

    private void box_despegable_placaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box_despegable_placaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_despegable_placaMousePressed

    private void box_despegable_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_despegable_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_despegable_placaActionPerformed

    private void btn_actualizar_lista_placaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizar_lista_placaMouseEntered
        btn_actualizar_lista_placa.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_actualizar_lista_placaMouseEntered

    private void btn_actualizar_lista_placaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizar_lista_placaMouseExited
        btn_actualizar_lista_placa.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_actualizar_lista_placaMouseExited

    private void btn_actualizar_lista_placaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizar_lista_placaMousePressed
        new ControlUsuario().llenarListaBoxFacturaPlaca(box_despegable_placa);
    }//GEN-LAST:event_btn_actualizar_lista_placaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JTextField Box_Describa_pago;
    private javax.swing.JLabel Cliente;
    private javax.swing.JPanel Generar_pago;
    private javax.swing.JLabel Placas;
    public static javax.swing.JComboBox<String> box_despegable_nom;
    public static javax.swing.JComboBox<String> box_despegable_placa;
    private javax.swing.JTextField box_valor_Cancelar_Pago;
    private javax.swing.JLabel btn_actualizar_ista;
    private javax.swing.JLabel btn_actualizar_lista_placa;
    private javax.swing.JLabel btn_generar_pago;
    private javax.swing.JSeparator jSeparatorIdentificacion;
    private Vista.PanelesRedondeados panel_pagos;
    private Vista.PanelesRedondeados panelesRedondeados1;
    private Vista.PanelesRedondeados panelesRedondeados2;
    private javax.swing.JLabel txt_Vehiculo1;
    private javax.swing.JLabel txt_pagos;
    private javax.swing.JLabel valor_cancela;
    public Vista.PanelesRedondeados ver_Actualizar_placa;
    public Vista.PanelesRedondeados ver_Actualizar_propietario;
    // End of variables declaration//GEN-END:variables
}
