
package Vista;

import java.awt.Color;
public class Factura extends javax.swing.JPanel {

    /**
     * Creates new form Factura
     */
    public Factura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        panel_pagos = new Vista.PanelesRedondeados();
        panelesRedondeados1 = new Vista.PanelesRedondeados();
        txt_cobrar = new javax.swing.JLabel();
        Cliente = new javax.swing.JLabel();
        Placas = new javax.swing.JLabel();
        valor_cancela = new javax.swing.JLabel();
        box_cliente_pago = new javax.swing.JTextField();
        box_Placa_pago = new javax.swing.JTextField();
        box_valor_Cancelar_Pago = new javax.swing.JTextField();
        jSeparatorNombre = new javax.swing.JSeparator();
        jSeparatorApellido = new javax.swing.JSeparator();
        jSeparatorIdentificacion = new javax.swing.JSeparator();
        Descripcion = new javax.swing.JLabel();
        Modificar = new javax.swing.JPanel();
        btn_modificar_pago = new javax.swing.JLabel();
        Cobrar = new javax.swing.JPanel();
        btn_Cobro_pago = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(780, 540));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_pagos.setBackground(new java.awt.Color(235, 235, 235));
        panel_pagos.setBordeInferiorDerecho(50);
        panel_pagos.setBordeInferiorIzquierdo(50);
        panel_pagos.setBordeSuperiorDerecho(50);
        panel_pagos.setBordeSuperiorIzquierdo(50);
        panel_pagos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelesRedondeados1.setBackground(new java.awt.Color(200, 200, 200));
        panelesRedondeados1.setBordeInferiorDerecho(50);
        panelesRedondeados1.setBordeInferiorIzquierdo(50);
        panelesRedondeados1.setBordeSuperiorDerecho(50);
        panelesRedondeados1.setBordeSuperiorIzquierdo(50);
        panelesRedondeados1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cobrar.setBackground(new java.awt.Color(187, 187, 187));
        txt_cobrar.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txt_cobrar.setForeground(new java.awt.Color(0, 0, 0));
        txt_cobrar.setText("Cobrar ");
        panelesRedondeados1.add(txt_cobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        Cliente.setBackground(new java.awt.Color(0, 0, 0));
        Cliente.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Cliente.setForeground(new java.awt.Color(0, 0, 0));
        Cliente.setText("Cliente");
        panelesRedondeados1.add(Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        Placas.setBackground(new java.awt.Color(0, 0, 0));
        Placas.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Placas.setForeground(new java.awt.Color(0, 0, 0));
        Placas.setText("Placa");
        panelesRedondeados1.add(Placas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        valor_cancela.setBackground(new java.awt.Color(0, 0, 0));
        valor_cancela.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        valor_cancela.setForeground(new java.awt.Color(0, 0, 0));
        valor_cancela.setText("Valor a cancelar");
        panelesRedondeados1.add(valor_cancela, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        box_cliente_pago.setBackground(new java.awt.Color(200, 200, 200));
        box_cliente_pago.setForeground(new java.awt.Color(0, 0, 0));
        box_cliente_pago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        box_cliente_pago.setBorder(null);
        box_cliente_pago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                box_cliente_pagoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box_cliente_pagoMousePressed(evt);
            }
        });
        box_cliente_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_cliente_pagoActionPerformed(evt);
            }
        });
        panelesRedondeados1.add(box_cliente_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 300, -1));

        box_Placa_pago.setBackground(new java.awt.Color(200, 200, 200));
        box_Placa_pago.setForeground(new java.awt.Color(0, 0, 0));
        box_Placa_pago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        box_Placa_pago.setBorder(null);
        box_Placa_pago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box_Placa_pagoMousePressed(evt);
            }
        });
        box_Placa_pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_Placa_pagoActionPerformed(evt);
            }
        });
        panelesRedondeados1.add(box_Placa_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 300, -1));

        box_valor_Cancelar_Pago.setBackground(new java.awt.Color(200, 200, 200));
        box_valor_Cancelar_Pago.setForeground(new java.awt.Color(0, 0, 0));
        box_valor_Cancelar_Pago.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        box_valor_Cancelar_Pago.setBorder(null);
        box_valor_Cancelar_Pago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box_valor_Cancelar_PagoMousePressed(evt);
            }
        });
        box_valor_Cancelar_Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_valor_Cancelar_PagoActionPerformed(evt);
            }
        });
        panelesRedondeados1.add(box_valor_Cancelar_Pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 300, -1));
        panelesRedondeados1.add(jSeparatorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 350, 10));
        panelesRedondeados1.add(jSeparatorApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 350, 10));
        panelesRedondeados1.add(jSeparatorIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 350, 10));

        Descripcion.setBackground(new java.awt.Color(0, 0, 0));
        Descripcion.setForeground(new java.awt.Color(235, 235, 235));
        panelesRedondeados1.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 400, 70));

        panel_pagos.add(panelesRedondeados1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 570, 360));

        Modificar.setBackground(new java.awt.Color(18, 90, 173));
        Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModificarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ModificarMousePressed(evt);
            }
        });
        Modificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_modificar_pago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_modificar_pago.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar_pago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_modificar_pago.setText("Modificar ");
        btn_modificar_pago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_modificar_pagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_modificar_pagoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_modificar_pagoMousePressed(evt);
            }
        });
        Modificar.add(btn_modificar_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        panel_pagos.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 140, 30));

        Cobrar.setBackground(new java.awt.Color(18, 90, 173));
        Cobrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cobrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CobrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CobrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CobrarMousePressed(evt);
            }
        });
        Cobrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Cobro_pago.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Cobro_pago.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cobro_pago.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Cobro_pago.setText("Cobrar");
        btn_Cobro_pago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Cobro_pagoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Cobro_pagoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_Cobro_pagoMousePressed(evt);
            }
        });
        Cobrar.add(btn_Cobro_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        panel_pagos.add(Cobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 140, 30));

        Background.add(panel_pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 750, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void box_cliente_pagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box_cliente_pagoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_box_cliente_pagoMouseExited

    private void box_cliente_pagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box_cliente_pagoMousePressed
        
    }//GEN-LAST:event_box_cliente_pagoMousePressed

    private void box_cliente_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_cliente_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_cliente_pagoActionPerformed

    private void box_Placa_pagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box_Placa_pagoMousePressed
       
    }//GEN-LAST:event_box_Placa_pagoMousePressed

    private void box_Placa_pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_Placa_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_Placa_pagoActionPerformed

    private void box_valor_Cancelar_PagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box_valor_Cancelar_PagoMousePressed
        
    }//GEN-LAST:event_box_valor_Cancelar_PagoMousePressed

    private void box_valor_Cancelar_PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_valor_Cancelar_PagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_valor_Cancelar_PagoActionPerformed

    private void ModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarMouseEntered

    private void ModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarMouseExited

    private void ModificarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModificarMousePressed

    private void btn_modificar_pagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificar_pagoMouseEntered
         Modificar.setBackground(new Color(46, 134, 193));
        btn_modificar_pago.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_modificar_pagoMouseEntered

    private void btn_modificar_pagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificar_pagoMouseExited
        Modificar.setBackground(new Color(18, 90, 173));
        btn_modificar_pago.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_modificar_pagoMouseExited

    private void btn_modificar_pagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificar_pagoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificar_pagoMousePressed

    private void CobrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CobrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_CobrarMouseEntered

    private void CobrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CobrarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CobrarMouseExited

    private void CobrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CobrarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_CobrarMousePressed

    private void btn_Cobro_pagoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cobro_pagoMouseEntered
        Cobrar.setBackground(new Color(115, 198, 182));
        btn_modificar_pago.setForeground(new Color(255, 255, 255));
    
    }//GEN-LAST:event_btn_Cobro_pagoMouseEntered

    private void btn_Cobro_pagoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cobro_pagoMouseExited
        Cobrar.setBackground(new Color(18, 90, 173));
        btn_Cobro_pago.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_Cobro_pagoMouseExited

    private void btn_Cobro_pagoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Cobro_pagoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Cobro_pagoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Cliente;
    private javax.swing.JPanel Cobrar;
    private javax.swing.JLabel Descripcion;
    private javax.swing.JPanel Modificar;
    private javax.swing.JLabel Placas;
    private javax.swing.JTextField box_Placa_pago;
    private javax.swing.JTextField box_cliente_pago;
    private javax.swing.JTextField box_valor_Cancelar_Pago;
    private javax.swing.JLabel btn_Cobro_pago;
    private javax.swing.JLabel btn_modificar_pago;
    private javax.swing.JSeparator jSeparatorApellido;
    private javax.swing.JSeparator jSeparatorIdentificacion;
    private javax.swing.JSeparator jSeparatorNombre;
    private Vista.PanelesRedondeados panel_pagos;
    private Vista.PanelesRedondeados panelesRedondeados1;
    private javax.swing.JLabel txt_cobrar;
    private javax.swing.JLabel valor_cancela;
    // End of variables declaration//GEN-END:variables
}
