/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author ivana
 */
public class Usuario extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        panel_usuario = new Vista.PanelesRedondeados();
        jSeparator2 = new javax.swing.JSeparator();
        txt_usuario = new javax.swing.JLabel();
        Buscador_Usuario = new javax.swing.JPanel();
        btn_Buscador_Usuario = new javax.swing.JLabel();
        Tabla_Usuarios = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        box_busqueda_usuario = new javax.swing.JTextField();
        eliminar_usuario = new javax.swing.JPanel();
        btn_eliminar_usuario = new javax.swing.JLabel();
        modificar_usuario = new javax.swing.JPanel();
        btn_modificar_usuario = new javax.swing.JLabel();
        agregar_usuario = new javax.swing.JPanel();
        btn_agregar_usuario = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(780, 540));

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_usuario.setBackground(new java.awt.Color(235, 235, 235));
        panel_usuario.setForeground(new java.awt.Color(250, 250, 250));
        panel_usuario.setBordeInferiorDerecho(50);
        panel_usuario.setBordeInferiorIzquierdo(50);
        panel_usuario.setBordeSuperiorDerecho(50);
        panel_usuario.setBordeSuperiorIzquierdo(50);
        panel_usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(250, 10));
        panel_usuario.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 620, 20));

        txt_usuario.setBackground(new java.awt.Color(187, 187, 187));
        txt_usuario.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txt_usuario.setText("Usuarios");
        panel_usuario.add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        Buscador_Usuario.setBackground(new java.awt.Color(18, 90, 173));
        Buscador_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buscador_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Buscador_UsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Buscador_UsuarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Buscador_UsuarioMousePressed(evt);
            }
        });
        Buscador_Usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Buscador_Usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Buscador_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_Buscador_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_Buscador_Usuario.setText("Buscar");
        btn_Buscador_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_Buscador_UsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_Buscador_UsuarioMouseExited(evt);
            }
        });
        Buscador_Usuario.add(btn_Buscador_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 0, 60, 30));

        panel_usuario.add(Buscador_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 70, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Marca", "Placa", "Color", "Fotografia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla_Usuarios.setViewportView(jTable1);

        panel_usuario.add(Tabla_Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 700, 310));

        box_busqueda_usuario.setBackground(new java.awt.Color(235, 235, 235));
        box_busqueda_usuario.setForeground(new java.awt.Color(102, 102, 102));
        box_busqueda_usuario.setText("Ingrese el nombre del usuario a buscar");
        box_busqueda_usuario.setBorder(null);
        box_busqueda_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                box_busqueda_usuarioMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                box_busqueda_usuarioMouseReleased(evt);
            }
        });
        box_busqueda_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box_busqueda_usuarioActionPerformed(evt);
            }
        });
        panel_usuario.add(box_busqueda_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 610, 20));

        eliminar_usuario.setBackground(new java.awt.Color(18, 90, 173));
        eliminar_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eliminar_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                eliminar_usuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                eliminar_usuarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eliminar_usuarioMousePressed(evt);
            }
        });
        eliminar_usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_eliminar_usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_eliminar_usuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_eliminar_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_eliminar_usuario.setText("Eliminar");
        btn_eliminar_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_eliminar_usuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_eliminar_usuarioMouseExited(evt);
            }
        });
        eliminar_usuario.add(btn_eliminar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        panel_usuario.add(eliminar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 90, 30));

        modificar_usuario.setBackground(new java.awt.Color(18, 90, 173));
        modificar_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modificar_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                modificar_usuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                modificar_usuarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                modificar_usuarioMousePressed(evt);
            }
        });
        modificar_usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_modificar_usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_modificar_usuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_modificar_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_modificar_usuario.setText("Modificar");
        btn_modificar_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_modificar_usuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_modificar_usuarioMouseExited(evt);
            }
        });
        modificar_usuario.add(btn_modificar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        panel_usuario.add(modificar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 90, 30));

        agregar_usuario.setBackground(new java.awt.Color(18, 90, 173));
        agregar_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                agregar_usuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregar_usuarioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                agregar_usuarioMousePressed(evt);
            }
        });
        agregar_usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_agregar_usuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_agregar_usuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_agregar_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_agregar_usuario.setText("Agregar");
        btn_agregar_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_agregar_usuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_agregar_usuarioMouseExited(evt);
            }
        });
        agregar_usuario.add(btn_agregar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 30));

        panel_usuario.add(agregar_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 90, 30));

        Background.add(panel_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 15, 750, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Buscador_UsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buscador_UsuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Buscador_UsuarioMouseEntered

    private void Buscador_UsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buscador_UsuarioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Buscador_UsuarioMouseExited

    private void Buscador_UsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buscador_UsuarioMousePressed

    }//GEN-LAST:event_Buscador_UsuarioMousePressed

    private void box_busqueda_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box_busqueda_usuarioMousePressed
        if (box_busqueda_usuario.getText().equals("Ingrese el nombre del usuario a buscar")) {
            box_busqueda_usuario.setText("");
        }
        box_busqueda_usuario.setForeground(Color.black);
    }//GEN-LAST:event_box_busqueda_usuarioMousePressed

    private void box_busqueda_usuarioMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_box_busqueda_usuarioMouseReleased
        //nothing
    }//GEN-LAST:event_box_busqueda_usuarioMouseReleased

    private void box_busqueda_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box_busqueda_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_box_busqueda_usuarioActionPerformed

    private void eliminar_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_usuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_usuarioMouseEntered

    private void eliminar_usuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_usuarioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_usuarioMouseExited

    private void eliminar_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminar_usuarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminar_usuarioMousePressed

    private void agregar_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_usuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_usuarioMouseEntered

    private void agregar_usuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_usuarioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_usuarioMouseExited

    private void agregar_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregar_usuarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregar_usuarioMousePressed

    private void modificar_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar_usuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_usuarioMouseEntered

    private void modificar_usuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar_usuarioMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_usuarioMouseExited

    private void modificar_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificar_usuarioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificar_usuarioMousePressed

    private void btn_eliminar_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminar_usuarioMouseEntered
        eliminar_usuario.setBackground(new Color(236, 112, 99));
        btn_eliminar_usuario.setForeground(new Color(255, 255, 255));


    }//GEN-LAST:event_btn_eliminar_usuarioMouseEntered

    private void btn_eliminar_usuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminar_usuarioMouseExited
        eliminar_usuario.setBackground(new Color(18, 90, 173));
        btn_eliminar_usuario.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_eliminar_usuarioMouseExited

    private void btn_agregar_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar_usuarioMouseEntered
        agregar_usuario.setBackground(new Color(115, 198, 182));
        btn_agregar_usuario.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_agregar_usuarioMouseEntered

    private void btn_agregar_usuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_agregar_usuarioMouseExited
        agregar_usuario.setBackground(new Color(18, 90, 173));
        btn_agregar_usuario.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_agregar_usuarioMouseExited

    private void btn_modificar_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificar_usuarioMouseEntered
        modificar_usuario.setBackground(new Color(46, 134, 193));
        btn_modificar_usuario.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_modificar_usuarioMouseEntered

    private void btn_modificar_usuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_modificar_usuarioMouseExited
        modificar_usuario.setBackground(new Color(18, 90, 173));
        btn_modificar_usuario.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_modificar_usuarioMouseExited

    private void btn_Buscador_UsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Buscador_UsuarioMouseEntered
        Buscador_Usuario.setBackground(new Color(31, 97, 141));
        btn_modificar_usuario.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_Buscador_UsuarioMouseEntered

    private void btn_Buscador_UsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Buscador_UsuarioMouseExited
        Buscador_Usuario.setBackground(new Color(18, 90, 173));
        btn_modificar_usuario.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_Buscador_UsuarioMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Buscador_Usuario;
    private javax.swing.JScrollPane Tabla_Usuarios;
    private javax.swing.JPanel agregar_usuario;
    private javax.swing.JTextField box_busqueda_usuario;
    private javax.swing.JLabel btn_Buscador_Usuario;
    private javax.swing.JLabel btn_agregar_usuario;
    private javax.swing.JLabel btn_eliminar_usuario;
    private javax.swing.JLabel btn_modificar_usuario;
    private javax.swing.JPanel eliminar_usuario;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel modificar_usuario;
    private Vista.PanelesRedondeados panel_usuario;
    private javax.swing.JLabel txt_usuario;
    // End of variables declaration//GEN-END:variables
}
